# Exercício Python no notebook Google Colab

ATENÇÃO: Primeiro copie esse notebook para sua área, resolva-o e retorne o seu link no formulário, não esquecendo de compartilhar o seu notebook Colab com qualquer pessoa que tenha acesso ao link.

## Preencha seu nome e email:

Nome: Filipe de Castro Borges da Silveira

Email: filipebcs8@gmail.com

## Enunciado
Você receberá uma matriz (uma lista de listas) de, possivelmente, altura e largura diferentes contendo apenas `0`s e `1`s. Cada `0` representa terra e cada `1` representa água. Uma lagoa é composta por qualquer número de `1`s verticalmente ou horizontalmente adjacentes (mas não diagonalmente adjacentes). O número de `1`s adjacentes determina a área da lagoa.

Escreva uma função que retorna uma lista com as áreas das lagoas contidas na matriz em ordem crescente.

Um exemplo é:

Dada a matriz

```
matrix = [
    [1, 1, 0, 1, 0],
    [1, 0, 1, 0, 0],
    [0, 0, 1, 0, 1],
    [1, 0, 1, 0, 1],
    [1, 0, 1, 1, 0]
]
```
A resposta esperada é uma lista com os tamanhos dos rios

```
sizes = [1, 2, 2, 3, 5]
```

Os critérios de avaliação são legibilidade do código e corretude do algoritmo, outros aspectos como performance e técnicas de programação não serão avaliados.

Você pode usar qualquer função built-in do python, pode utilizar funções auxiliares, criar classes e etc. Deve-se apenas manter a assinatura da função `lake_areas`. Na dúvida, submeter sua melhor tentativa documentando seu raciocínio é melhor do que não submeter nada :)

In [1]:
from typing import List

def lake_areas(matrix: List[List[int]]) -> List[int]:
    # Write your code here.
    pass

In [2]:
# Importar bibliotecas relevantes
import numpy as np
import itertools
import pandas as pd

In [3]:
# Definir a matriz de lagos original
matrix = [
    [1, 1, 0, 1, 0],
    [1, 0, 1, 0, 0],
    [0, 0, 1, 0, 1],
    [1, 0, 1, 0, 1],
    [1, 0, 1, 1, 0]
]
matrix = np.array(matrix)

In [4]:
# Definir a matriz de lagos de teste
matrix_2 = [
    [1, 1, 0, 1, 0, 0],
    [1, 0, 1, 0, 0, 1],
    [0, 1, 1, 0, 1, 0],
    [1, 0, 1, 0, 1, 0],
    [1, 0, 1, 1, 0, 1]
]
matrix_2 = np.array(matrix_2)
#lastRow = len(matrix_2) - 1
#lastColumn = len(matrix_2[0]) - 1


In [5]:
# Inicializar os rótulos dos grupos
grupo = 1

# Inicializar arrays vazios
colunas = []
linhas = []
posicoes = []

In [6]:
# Identificar as respectivas linhas e colunas de cada entrada '1' na matriz
for i in range(matrix_2.shape[0]):
    
    for j in range(matrix_2.shape[1]):
    
        if matrix_2[i][j] == 1:
            #entradas.append([i, j])
            linhas.append(i)
            colunas.append(j)

In [7]:
# Monta um array com as posições das entradas '1' no formato "['linha', 'coluna']"
posicoes = np.column_stack((np.array(linhas), np.array(colunas)))
posicoes

array([[0, 0],
       [0, 1],
       [0, 3],
       [1, 0],
       [1, 2],
       [1, 5],
       [2, 1],
       [2, 2],
       [2, 4],
       [3, 0],
       [3, 2],
       [3, 4],
       [4, 0],
       [4, 2],
       [4, 3],
       [4, 5]])

In [8]:
posicoesGrupo = np.zeros(len(posicoes))
posicoesGrupo[0] = 1
posicoesGrupo

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
# Montar matriz cujas colunas 0 e 1 são o ponto de referência e coluna 2 e 3 são o ponto comparador
for referencia in range(posicoes.shape[0]):
    print(referencia)
    
    for comparador in range(referencia+1, posicoes.shape[0]):
        
        if posicoesGrupo[referencia] == 0:
            posicoesGrupo[referencia] = max(posicoesGrupo)+1
        
        # Calcular a distância entre o ponto de referência e o ponto comparador
        posicaoRelativa = np.sum(abs(posicoes[referencia] - posicoes[comparador]))
        
        if posicaoRelativa <= 1:
            
            if posicoesGrupo[comparador] == 0:
                posicoesGrupo[comparador] = posicoesGrupo[referencia]
                
            if posicoesGrupo[comparador] != posicoesGrupo[referencia]:
                posicoesGrupo[referencia] = min(posicoesGrupo[referencia], posicoesGrupo[comparador])
        
    if referencia == len(posicoesGrupo)-1:
        posicoesGrupo[-1] = max(posicoesGrupo)+1

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [10]:
posicoesGrupo

array([1., 1., 2., 1., 3., 4., 3., 3., 5., 6., 3., 5., 6., 3., 3., 7.])