# Exercício Python no notebook Google Colab

ATENÇÃO: Primeiro copie esse notebook para sua área, resolva-o e retorne o seu link no formulário, não esquecendo de compartilhar o seu notebook Colab com qualquer pessoa que tenha acesso ao link.

## Preencha seu nome e email:

Nome: Filipe de Castro Borges da Silveira

Email: filipebcs8@gmail.com

## Enunciado
Você receberá uma matriz (uma lista de listas) de, possivelmente, altura e largura diferentes contendo apenas `0`s e `1`s. Cada `0` representa terra e cada `1` representa água. Uma lagoa é composta por qualquer número de `1`s verticalmente ou horizontalmente adjacentes (mas não diagonalmente adjacentes). O número de `1`s adjacentes determina a área da lagoa.

Escreva uma função que retorna uma lista com as áreas das lagoas contidas na matriz em ordem crescente.

Um exemplo é:

Dada a matriz

```
matrix = [
    [1, 1, 0, 1, 0],
    [1, 0, 1, 0, 0],
    [0, 0, 1, 0, 1],
    [1, 0, 1, 0, 1],
    [1, 0, 1, 1, 0]
]
```
A resposta esperada é uma lista com os tamanhos dos rios

```
sizes = [1, 2, 2, 3, 5]
```

Os critérios de avaliação são legibilidade do código e corretude do algoritmo, outros aspectos como performance e técnicas de programação não serão avaliados.

Você pode usar qualquer função built-in do python, pode utilizar funções auxiliares, criar classes e etc. Deve-se apenas manter a assinatura da função `lake_areas`. Na dúvida, submeter sua melhor tentativa documentando seu raciocínio é melhor do que não submeter nada :)

In [4]:
from typing import List

def lake_areas(matrix: List[List[int]]) -> List[int]:
    # Write your code here.
    pass

In [5]:
matrix = [
    [1, 1, 0, 1, 0],
    [1, 0, 1, 0, 0],
    [0, 0, 1, 0, 1],
    [1, 0, 1, 0, 1],
    [1, 0, 1, 1, 0]
]

In [2]:
matrix

[[1, 1, 0, 1, 0],
 [1, 0, 1, 0, 0],
 [0, 0, 1, 0, 1],
 [1, 0, 1, 0, 1],
 [1, 0, 1, 1, 0]]

In [30]:

# Classe que conta o número de lagos em uma determinada área
class Area:

    # Inicilializando as variáveis
    def __init__(self, lin, col, area):
        self.LIN = lin
        self.COL = col
        self.area = area
        
    # Função que verifica se os valores delinha e coluna são válidos para a posição e se essa posição já foi visitada
    def dentroLimites(self, i, j, visitado):
        # Linha e coluna não menores do que zero e não maiores do que o limite da área e se essa posição já foi
        # visitada
        return (i >= 0 and i < self.LIN and j >= 0 and j < self.COL and not visitado[i][j] and self.area[i][j])
    
    # Função que implementa o algoritmo 'depth-first search' para uma matriz 2D de booleanos. Apenas os 2 vizinhos
    # na horizontal e os 2 vizinhos na vertical são considerados
    def DFS(self, i, j, visitado):
        
        # Listas com os deslocamentos necessários para os 4 vizinhos considerados: 2 verticais e 2 horizontais
        nLinha = [-1,  0, 0,  1];
        nColuna = [ 0, -1, 1,  0];
        
        # Marcar posição como visitada
        visitado[i][j] = True
        
        # Aplicar o algoritmo 'depth-first' search nos vizinhos da horizontal e da vertical
        for k in range(4):
            if self.dentroLimites(i + nLinha[k], j + nColuna[k], visitado):
                self.DFS(i + nLinha[k], j + nColuna[k], visitado)

    # Função que retorna o número de lagos em uma determinada área
    def contarLagos(self):
        # Criar um array booleano que registra as posições que foram visitadas (inicialmente, todas as células estão
        # marcadas como NÃO-visitadas)
        visitado = [[False for j in range(self.COL)]for i in range(self.LIN)]

        # Inicializar o contador em zero e percorrer as posições da matriz
        nLagos = 0
        for i in range(self.LIN):
            for j in range(self.COL):
                # Checar se a posição contém o valor 1 e se ela ainda não foi visitada. Se ambas as condições forem
                # cumpridas, conta-se mais um lago
                if visitado[i][j] == False and self.area[i][j] == 1:
                    # Visitar todas as células no lago e incrementar o contador de lagos
                    self.DFS(i, j, visitado)
                    nLagos += 1
            print(j)

        print(visitado)
        return nLagos

# Definir a área que será analisada onde:
# - 0 representa terra
# - 1 representa lago
area = [
    [1, 1, 0, 0, 0, 1],
    [0, 1, 0, 0, 1, 0],
    [1, 0, 0, 1, 1, 1],
    [0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 1, 1],
    [1, 0, 0, 1, 0, 1]
]

# Extrair o número de linha e colunas na matriz que representa a área
lin = len(area)
col = len(area[0])

# Chamar a classe 'Area'
area = Area(lin, col, area)

# Identificar o número de lagos na área designada
print ("O número de lagos na área é:", area.contarLagos())

5 

5 

5 

5 

5 

5 

[[True, True, False, False, False, True], [False, True, False, False, True, False], [True, False, False, True, True, True], [False, False, False, False, False, False], [True, False, True, False, True, True], [True, False, False, True, False, True]]
O número de lagos na área é: 8


In [101]:
import numpy as np

area = [
    [1, 1, 0, 0, 0, 1],
    [0, 1, 0, 0, 1, 0],
    [1, 0, 0, 1, 1, 1],
    [0, 0, 0, 0, 0, 0],
    [1, 0, 1, 0, 1, 1]
]

In [133]:
numberingIslands = np.zeros(np.shape(area))
labelCont = 1
labels = []

for i in range(len(area)):
    
    for j in range(len(area[0])):
    
        if area[i][j] == 1:
    
            if i == 0 and j == 0:
                numberingIslands[i][j] = labelCont
                labels.append(labelCont)
                labelCont += 1
        
            if i == 0 and j > 0:
                
                if j == len(area[0]):
                    continue
        
                if area[i][j-1] == 1:
                    numberingIslands[i][j] = numberingIslands[i][j-1]
        
                if not area[i][j-1] == 1:
                    numberingIslands[i][j] = labelCont
                    labels.append(labelCont)
                    labelCont += 1
        
            if i > 0 and j == 0:
                
                if area[i-1][j] == 1:
                    numberingIslands[i][j] = numberingIslands[i-1][j]
                
                else:
                    numberingIslands[i][j] =  labelCont
                    labels.append(labelCont)
                    labelCont += 1
        
            if i > 0 and j > 0:
        
                if area[i-1][j] == 1 and area[i][j-1] == 1:
                    numberingIslands[i][j] = numberingIslands[i-1][j]
        
                if area[i-1][j] == 1 and area[i][j-1] == 0:
                    numberingIslands[i][j] = numberingIslands[i-1][j]
        
                if area[i-1][j] == 0 and area[i][j-1] == 1:
                    numberingIslands[i][j] = numberingIslands[i][j-1]
                    
                else:
                    numberingIslands[i][j] = labelCont
                    labels.append(labelCont)
                    labelCont += 1
                    
                
        
        else:
            continue
            
    #if i == 2:
    #    break
        
print(area)
print(numberingIslands)

1 1
[[1, 1, 0, 0, 0, 1], [0, 1, 0, 0, 1, 0], [1, 0, 0, 1, 1, 1], [0, 0, 0, 0, 0, 0], [1, 0, 1, 0, 1, 1]]
[[ 1.  1.  0.  0.  0.  2.]
 [ 0.  3.  0.  0.  4.  0.]
 [ 5.  0.  0.  6.  7.  7.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 8.  0.  9.  0. 10. 10.]]


In [118]:
area

5

In [76]:
print(len(area))
print(len(area[0]))

5
6
