# Exercício Python no notebook Google Colab

ATENÇÃO: Primeiro copie esse notebook para sua área, resolva-o e retorne o seu link no formulário, não esquecendo de compartilhar o seu notebook Colab com qualquer pessoa que tenha acesso ao link.

## Preencha seu nome e email:

Nome: Filipe de Castro Borges da Silveira

Email: filipebcs8@gmail.com

## Enunciado
Você receberá uma matriz (uma lista de listas) de, possivelmente, altura e largura diferentes contendo apenas `0`s e `1`s. Cada `0` representa terra e cada `1` representa água. Uma lagoa é composta por qualquer número de `1`s verticalmente ou horizontalmente adjacentes (mas não diagonalmente adjacentes). O número de `1`s adjacentes determina a área da lagoa.

Escreva uma função que retorna uma lista com as áreas das lagoas contidas na matriz em ordem crescente.

Um exemplo é:

Dada a matriz

```
matrix = [
    [1, 1, 0, 1, 0],
    [1, 0, 1, 0, 0],
    [0, 0, 1, 0, 1],
    [1, 0, 1, 0, 1],
    [1, 0, 1, 1, 0]
]
```
A resposta esperada é uma lista com os tamanhos dos rios

```
sizes = [1, 2, 2, 3, 5]
```

Os critérios de avaliação são legibilidade do código e corretude do algoritmo, outros aspectos como performance e técnicas de programação não serão avaliados.

Você pode usar qualquer função built-in do python, pode utilizar funções auxiliares, criar classes e etc. Deve-se apenas manter a assinatura da função `lake_areas`. Na dúvida, submeter sua melhor tentativa documentando seu raciocínio é melhor do que não submeter nada :)

In [622]:
from typing import List

def lake_areas(matrix: List[List[int]]) -> List[int]:
    # Write your code here.
    pass

In [623]:
# Importar bibliotecas relevantes
import numpy as np
import itertools

In [624]:
# Definir a matriz de lagos original
matrix = [
    [1, 1, 0, 1, 0],
    [1, 0, 1, 0, 0],
    [0, 0, 1, 0, 1],
    [1, 0, 1, 0, 1],
    [1, 0, 1, 1, 0]
]
matrix = np.array(matrix)

In [625]:
# Definir a matriz de lagos de teste
matrix_2 = [
    [1, 1, 0, 1, 0, 0],
    [1, 0, 1, 0, 0, 1],
    [0, 1, 1, 0, 1, 0],
    [1, 0, 1, 0, 1, 0],
    [1, 0, 1, 1, 0, 1]
]
matrix_2 = np.array(matrix_2)
#lastRow = len(matrix_2) - 1
#lastColumn = len(matrix_2[0]) - 1


In [626]:
# Inicializar os rótulos dos grupos
grupo = 1
ultimoGrupo = 1

# Inicializar arrays vazios
colunas = []
linhas = []
vizinhos = []
vizinhosReferencia = []
vizinhosComparador = []
grupoReferencia = []
grupoComparador = []
posicoes = []
registro = []
registroGrupos = []
entradas = []

# Criar uma nova matriz de mesmas dimensões para armazenar a classificação em grupos
matrixGrupos = np.zeros(matrix_2.shape)

In [627]:
# Identificar as respectivas linhas e colunas de cada entrada '1' na matriz
for i in range(matrix_2.shape[0]):
    
    for j in range(matrix_2.shape[1]):
    
        if matrix_2[i][j] == 1:
            #entradas.append([i, j])
            linhas.append(i)
            colunas.append(j)

In [628]:
# Monta um array com as posições das entradas '1' no formato "['linha', 'coluna']"
posicoes = np.column_stack((np.array(linhas), np.array(colunas)))

In [629]:
# Montar matriz cujas colunas 0 e 1 são o ponto de referência e coluna 2 e 3 são o ponto comparador
for referencia in range(posicoes.shape[0]):
    
    for comparador in range(referencia, posicoes.shape[0]):
        
        if (posicoes[referencia] == posicoes[comparador]).all():
            continue
        
        posicaoRelativa = np.sum(abs(posicoes[referencia] - posicoes[comparador]))
        
        if posicaoRelativa <= 1:
            #print('Referencia 0: %d\t Referencia 1: %d' % (referencia[0], referencia[1]))
            #vizinhos.append([posicoes[referencia][0], posicoes[referencia][1], 0, posicoes[comparador][0], posicoes[comparador][1], 0])
            vizinhosReferencia.append([posicoes[referencia][0], posicoes[referencia][1]])
            vizinhosComparador.append([posicoes[comparador][0], posicoes[comparador][1]])

In [630]:
vizinhosReferencia

[[0, 0], [0, 0], [1, 2], [2, 1], [2, 2], [2, 4], [3, 0], [3, 2], [4, 2]]

In [631]:
vizinhosComparador

[[0, 1], [1, 0], [2, 2], [2, 2], [3, 2], [3, 4], [4, 0], [4, 2], [4, 3]]

In [632]:
gruposReferencia = np.zeros(len(vizinhosReferencia))
gruposComparador = np.zeros(len(vizinhosComparador))

In [646]:
for conti, i in enumerate(vizinhosReferencia):
    print('\n')
    
    for contj, j in enumerate(vizinhosComparador):
        
        if (conti == 0) and (contj == 0):
            gruposReferencia[conti] = 1
            gruposComparador[contj] = 1
        
        elif (conti > 0) and (contj > 0):
            diferenca = np.sum(np.abs(np.array(i) - np.array(j)))
            
            

            print('Diferenca: ', diferenca)

print(conti)





Diferenca:  1
Diferenca:  4
Diferenca:  4
Diferenca:  5
Diferenca:  7
Diferenca:  4
Diferenca:  6
Diferenca:  7


Diferenca:  2
Diferenca:  1
Diferenca:  1
Diferenca:  2
Diferenca:  4
Diferenca:  5
Diferenca:  3
Diferenca:  4


Diferenca:  2
Diferenca:  1
Diferenca:  1
Diferenca:  2
Diferenca:  4
Diferenca:  3
Diferenca:  3
Diferenca:  4


Diferenca:  3
Diferenca:  0
Diferenca:  0
Diferenca:  1
Diferenca:  3
Diferenca:  4
Diferenca:  2
Diferenca:  3


Diferenca:  5
Diferenca:  2
Diferenca:  2
Diferenca:  3
Diferenca:  1
Diferenca:  6
Diferenca:  4
Diferenca:  3


Diferenca:  2
Diferenca:  3
Diferenca:  3
Diferenca:  2
Diferenca:  4
Diferenca:  1
Diferenca:  3
Diferenca:  4


Diferenca:  4
Diferenca:  1
Diferenca:  1
Diferenca:  0
Diferenca:  2
Diferenca:  3
Diferenca:  1
Diferenca:  2


Diferenca:  5
Diferenca:  2
Diferenca:  2
Diferenca:  1
Diferenca:  3
Diferenca:  2
Diferenca:  0
Diferenca:  1
8


In [634]:
np.sum(np.abs(np.array([0, 1]) - np.array([1, 1])))

1

In [635]:
matrix_2

array([[1, 1, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 1],
       [0, 1, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 1, 0, 1]])

In [636]:
vizinhosReferencia

[[0, 0], [0, 0], [1, 2], [2, 1], [2, 2], [2, 4], [3, 0], [3, 2], [4, 2]]

In [637]:
registro

[]

In [638]:
registro = []

for cont, _ in enumerate(vizinhosReferencia):
    
    if cont == 0:
        
        if vizinhosReferencia[cont] == vizinhosComparador[cont]:
            registro.append(vizinhosReferencia[cont])
            registroGrupos.append(grupo)
        
        else:
            registro.append(vizinhosReferencia[cont])
            registro.append(vizinhosComparador[cont])
            registroGrupos.append(grupo)
    
    else:
        
        if vizinhosReferencia[cont] not in registro:
            grupo += 1
            
            if vizinhosReferencia[cont] == vizinhosComparador[cont]:
                registro.append(vizinhosReferencia[cont])
                registroGrupos.append(grupo)
                
            else:
                registro.append(vizinhosReferencia[cont])
                registro.append(vizinhosComparador[cont])
                registroGrupos.append(grupo)
                registroGrupos.append(grupo)
            
        if vizinhosComparador[cont] not in registro:
            grupo += 1
            
            if vizinhosComparador[cont] == vizinhosReferencia[cont]:
                registro.append(vizinhosComparador[cont])
                registroGrupos.append(grupo)
                
            else:
                registro.append(vizinhosReferencia[cont])
                registro.append(vizinhosComparador[cont])
                registroGrupos.append(grupo)
                registroGrupos.append(grupo)
                
                

In [639]:
registro

[[0, 0],
 [0, 1],
 [0, 0],
 [1, 0],
 [1, 2],
 [2, 2],
 [2, 1],
 [2, 2],
 [2, 2],
 [3, 2],
 [2, 4],
 [3, 4],
 [3, 0],
 [4, 0],
 [3, 2],
 [4, 2],
 [4, 2],
 [4, 3]]

In [640]:
registroGrupos

[1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9]

In [641]:
grupo

9

column_to_insert = np.zeros(len(vizinhos))

vizinhosExpandido = vizinhos
vizinhosExpandido = np.insert(vizinhosExpandido, 2, column_to_insert, axis=1)
vizinhosExpandido = np.insert(vizinhosExpandido, vizinhosExpandido.shape[1], column_to_insert, axis=1)
vizinhosExpandido

registro = []

for cont, j in enumerate(vizinhosExpandido):
    #print(j[0:2])
    if cont == 0:
        #print(vizinhosExpandido)
        vizinhosExpandido[cont][2] = grupo
        vizinhosExpandido[cont][5] = grupo
        registro.append(list(vizinhosExpandido[cont][:2]))
        registro.append(list(vizinhosExpandido[cont][2:4]))
    if cont > 0:
        if (j[:2] == registro).all(axis=1).any() or (j[3:5] == registro).all(axis=1).any():
            vizinhosExpandido[cont][2] = grupo
            vizinhosExpandido[cont][5] = grupo
            registro.append(list(vizinhosExpandido[cont][:2]))
            registro.append(list(vizinhosExpandido[cont][2:4]))
        else:
            grupo += 1
            vizinhosExpandido[cont][2] = grupo
            vizinhosExpandido[cont][5] = grupo
            registro.append(list(vizinhosExpandido[cont][:2]))
            registro.append(list(vizinhosExpandido[cont][2:4]))

vizinhosExpandido = np.sort(np.concatenate(np.hsplit(vizinhosExpandido, 2))).tolist()
vizinhosExpandido

In [642]:
registro.sort()
registroSemDuplicados = list(registro for registro, _ in itertools.groupby(registro))

In [643]:
registro = []

for cont, j in enumerate(vizinhosExpandido):
    
    if cont == 0:
        vizinhosExpandido[cont][2] = grupo
        vizinhosExpandido[cont][5] = grupo
        registro.append(vizinhosExpandido[cont][:2])
        registro.append(vizinhosExpandido[cont][3:5])
        #print(registro)
    
    if cont > 0:
        
        if (j[:3] in registro) or (j[3:] in registro):
            vizinhosExpandido[cont][2] = grupo
            vizinhosExpandido[cont][5] = grupo
            registro.append(vizinhosExpandido[cont][:2])
            registro.append(vizinhosExpandido[cont][3:5])
        
        else:
            grupo += 1
            vizinhosExpandido[cont][2] = grupo
            vizinhosExpandido[cont][5] = grupo
            registro.append(vizinhosExpandido[cont][:2])
            registro.append(vizinhosExpandido[cont][3:5])
            
            
registro

[[0, 0],
 [0, 1],
 [0, 0],
 [1, 0],
 [1, 2],
 [2, 2],
 [2, 1],
 [2, 2],
 [2, 2],
 [3, 2],
 [2, 4],
 [3, 4],
 [3, 0],
 [4, 0],
 [3, 2],
 [4, 2],
 [4, 2],
 [4, 3]]

In [644]:
vizinhosExpandido

[[0, 0, 9, 0, 1, 9],
 [0, 0, 10, 1, 0, 10],
 [1, 2, 11, 2, 2, 11],
 [2, 1, 12, 2, 2, 12],
 [2, 2, 13, 3, 2, 13],
 [2, 4, 14, 3, 4, 14],
 [3, 0, 15, 4, 0, 15],
 [3, 2, 16, 4, 2, 16],
 [4, 2, 17, 4, 3, 17]]

In [645]:
registro = []

for cont, j in enumerate(vizinhosExpandido):
    
    if cont == 0:
        vizinhosExpandido[cont][2] = grupo
        vizinhosExpandido[cont][5] = grupo
        registro.append(vizinhosExpandido[cont][:3])
        registro.append(vizinhosExpandido[cont][2:5])
        #print(registro)
    
    if cont > 0:
        #print(cont)
        print(j[:3])
        print(registro[1])
        
        if (j[:3] == registro).all(axis=1).any() or (j[3:] == registro).all(axis=1).any():
            vizinhosExpandido[cont][2] = grupo
            vizinhosExpandido[cont][5] = grupo
            registro.append(vizinhosExpandido[cont][:3])
            registro.append(vizinhosExpandido[cont][2:4])
        
        else:
            grupo += 1
            vizinhosExpandido[cont][2] = grupo
            vizinhosExpandido[cont][5] = grupo
            registro.append(vizinhosExpandido[cont][:3])
            registro.append(vizinhosExpandido[cont][2:5])

registro

[0, 0, 10]
[17, 0, 1]


AttributeError: 'bool' object has no attribute 'all'

In [ ]:
registro

[[0, 0, 1], [1, 0, 1]]

In [ ]:
vizinhosExpandido

array([[0, 0, 1, 0, 1, 1],
       [0, 0, 1, 1, 0, 1],
       [1, 2, 2, 2, 2, 2],
       [2, 1, 2, 2, 2, 2],
       [2, 2, 2, 3, 2, 2],
       [2, 4, 3, 3, 4, 3],
       [3, 0, 4, 4, 0, 4],
       [3, 2, 5, 4, 2, 5],
       [4, 2, 6, 4, 3, 6]])

In [ ]:
check = np.array([0, 1])
comparison = (check == registro).all(axis=1).any()
comparison

False

In [ ]:
classifier = 1

for i in range(1, len(vizinhos)):
    pass

In [ ]:
vizinhos12 = vizinhos[:, 0:2]
vizinhos12

array([[0, 0],
       [0, 0],
       [1, 2],
       [2, 1],
       [2, 2],
       [2, 4],
       [3, 0],
       [3, 2],
       [4, 2]])

In [ ]:
vizinhos12[:]

array([[0, 0],
       [0, 0],
       [1, 2],
       [2, 1],
       [2, 2],
       [2, 4],
       [3, 0],
       [3, 2],
       [4, 2]])

In [ ]:
len(vizinhos)

9

In [ ]:
vizinhos34 = vizinhos[:, 2:]
vizinhos34

array([[1, 0, 1, 1],
       [1, 1, 0, 1],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 3, 2, 2],
       [3, 3, 4, 3],
       [4, 4, 0, 4],
       [5, 4, 2, 5],
       [6, 4, 3, 6]])

In [ ]:
vizinhosVertical = np.concatenate((vizinhos[:, 0:2], vizinhos[:, 2:]), axis=0)
vizinhosVertical.sort(axis=1)
vizinhosVertical = np.unique(vizinhosVertical, axis=0)
vizinhosVertical

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 4

In [ ]:
np.unique(vizinhosVertical, axis=0)

array([[0, 0],
       [0, 1],
       [0, 3],
       [0, 4],
       [1, 2],
       [2, 2],
       [2, 3],
       [2, 4],
       [3, 4]])